# 头部菜单，title: link
menu:
  标签云: /tags
  归档: /archives
  Latex查询: /latex
  友情链接: /friendlinks

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
#welcome_cover: /img/welcome-cover.jpg
welcome_cover: http://imglf5.nosdn0.126.net/img/MXRvbEU3WmxrOUo1RGkwOTlhTXJWTHpsUUg0SFNabEdqNXFEenpHK0diZ3gwTzJJR1hHZWVRPT0.jpg?imageView&thumbnail=1973y1200&type=jpg&quality=96&stripmeta=0&type=jpg
# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '49714482bda0b6273fc4'
    # 应用秘钥
    clientSecret: '3002f28762b656bd195de029eabbbf0e1015654c'
    # issue仓库名
    repo: 'blogtalk'
    # Github名
    owner: 'forever97'
    # Github名
    admin: ['forever97']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: forever97

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml

# MathJax Support
mathjax:
  enable: true
  per_page: true
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

# 是否开启访问量统计功能(不蒜子)
busuanzi:
 enable: true